#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [ -n "${ENABLE_ACARS}" ]; then

    set -o pipefail

    # Require that acarsdec is running
    if ! netstat -an | grep -P '^\s*udp\s+\d+\s+\d+\s+(?>\d{1,3}\.{0,1}){4}:\d{1,5}\s+127\.0\.0\.1:5550\s+\w+\s*$' > /dev/null; then
        if [ -n "${VERBOSE}" ]; then
            echo "Waiting for acarsdec" | stdbuf -o0 awk '{print "[acars_server] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
        fi
        sleep 1
        exit
    fi
    if [ -n "${VERBOSE}" ]; then
      echo "acarsdec ready, starting service" | stdbuf -o0 awk '{print "[acars_server] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi

    set -e

    # Listens for the output of acarsdec (UDP), and makes it available for multiple processes at TCP port 15550
    ncat -4 -u --wait 1 --listen 127.0.0.1 5550 | ncat -4 --keep-open --listen 127.0.0.1 15550 \
      2>&1 | stdbuf -o0 awk '{print "[acars_server] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    sleep 86400
fi
