#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o pipefail

# let's give the other database stuff a bit to do startup tasks
# due to sqlite database locking, this isn't critical and just for quicker startup of the other services
# also if this script causes an error, the service won't restart it quite as quickly
sleep 30

#shellcheck disable=SC2016
stdbuf -eL -oL python3 /scripts/prune_db.py 2>&1 | stdbuf -oL awk '{print "[database-upkeep] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}' || exit 1
