#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ -n "${ENABLE_ADSB}" ]; then
    set -e
    # Start the receiver
    # shellcheck disable=SC2016
    python3 /webapp/adsb.py \
        2>&1 | stdbuf -o0 awk '{print "[adsb_receiver] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

else
    sleep 86400
fi
