#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# if [ -n "${ENABLE_WEB}" ]; then
#   if [[ -n "${ENABLE_VDLM}" ]]; then
#     # Require that vdlm2_server is running
#     if ! netstat -an | grep -P '^\s*tcp\s+\d+\s+\d+\s+127\.0\.0\.1:15555\s+(?>\d{1,3}\.{0,1}){4}:\*\s+LISTEN\s*$' > /dev/null; then
#       if [ -z "${QUIET_LOGS}" ]; then
#           # shellcheck disable=SC2016
#           echo "Waiting for vdlm2_server" | stdbuf -o0 awk '{print "[webapp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
#       fi
#       sleep 1
#       exit
#     fi
#   fi

#   if [ -n "${ENABLE_ACARS}" ]; then
#     # Require that acars_server is running
#     if ! netstat -an | grep -P '^\s*tcp\s+\d+\s+\d+\s+127\.0\.0\.1:15550\s+(?>\d{1,3}\.{0,1}){4}:\*\s+LISTEN\s*$' > /dev/null; then
#       if [ -z "${QUIET_LOGS}" ]; then
#         # shellcheck disable=SC2016
#         echo "Waiting for acars_server" | stdbuf -o0 awk '{print "[webapp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
#       fi
#       sleep 1
#       exit
#     fi
#   fi    

  if [ -z "${QUIET_LOGS}" ]; then
    # shellcheck disable=SC2016
    echo "Starting web service" | stdbuf -o0 awk '{print "[webapp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
  fi

  pushd /webapp > /dev/null 2>&1 || exit 1

  # shellcheck disable=SC2016
  stdbuf -o0 gunicorn3 \
      -b "0.0.0.0:80" \
      -w 1 \
      --no-sendfile \
      -k eventlet \
      application:app \
    2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[webapp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
  # web server must be disabled. Go to sleep forever
  sleep 86400
fi
