[workspace]
members = ["rust/acarshub", "rust/database"]
resolver = "3"

[workspace.package]
version = "5.0.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.98"
diesel = { version = "2.2.10", features = ["sqlite"] }
diesel_migrations = { version = "2.2.0", features = ["sqlite"] }
libsqlite3-sys = { version = "0.33.0", features = ["bundled"] }
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
    "parking_lot",
] }
