#!/command/with-contenv bash
# shellcheck shell=bash

if [[ -n "${QUIET_LOGS}" ]]; then
    echo "########################################################"
    echo "QUIET_LOGS has been deprecated. Please use MIN_LOG_LEVEL"
    if [[ ${QUIET_LOGS,,} =~ false ]]; then
        echo "Please remove QUIET_LOGS to remove this warning and set MIN_LOG_LEVEL=4 to get back the logs you are expecting"
    else
        echo "Please remove QUIET_LOGS to remove this warning and set MIN_LOG_LEVEL=3 to get back the logs you are expecting"
    fi
    echo "########################################################"
fi

# Ensure /database dir is present

mkdir -p /database/images/static/images

# Ensure stats files are present
touch /database/vdlm2.past5min.json
touch /database/acars.past5min.json

exit 0
