#!/command/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC2154

# shellcheck disable=SC1091
source /scripts/common

if [[ -n "${QUIET_LOGS}" ]]; then
    "${s6wrap[@]}" echo "########################################################"
    "${s6wrap[@]}" echo "QUIET_LOGS has been deprecated. Please use MIN_LOG_LEVEL"
    if [[ ${QUIET_LOGS,,} =~ false ]]; then
        "${s6wrap[@]}" echo "Please remove QUIET_LOGS to remove this warning and set MIN_LOG_LEVEL=4 to get back the logs you are expecting"
    else
        "${s6wrap[@]}" echo "Please remove QUIET_LOGS to remove this warning and set MIN_LOG_LEVEL=3 to get back the logs you are expecting"
    fi
    "${s6wrap[@]}" echo "########################################################"
fi

if [[ ${ENABLE_ACARS,,} =~ "external" ]]; then
    "${s6wrap[@]}" echo "\"external\" for ENABLE_ACARS is deprecated. Please use \"true\" instead"
fi

if [[ ${ENABLE_VDLM,,} =~ "external" ]]; then
    "${s6wrap[@]}" echo "\"external\" for ENABLE_VDLM is deprecated. Please use \"true\" instead"
fi

if [[ ${ENABLE_HFDL,,} =~ "external" ]]; then
    "${s6wrap[@]}" echo "\"external\" for ENABLE_HFDL is deprecated. Please use \"true\" instead"
fi

if [[ ${ENABLE_IMSL,,} =~ "external" ]]; then
    "${s6wrap[@]}" echo "\"external\" for ENABLE_IMSL is deprecated. Please use \"true\" instead"
fi

if [[ ${ENABLE_IRDM,,} =~ "external" ]]; then
    "${s6wrap[@]}" echo "\"external\" for ENABLE_IRDM is deprecated. Please use \"true\" instead"
fi

# Ensure /database dir is present

mkdir -p /database/images/static/images

# Ensure stats files are present
touch /database/vdlm2.past5min.json
touch /database/acars.past5min.json

exit 0
