#!/command/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC2154

# shellcheck disable=SC1091
source /scripts/common

if [[ ! -e /nginx-ranonce ]]; then
    cp /etc/nginx.acarshub/sites-enabled/acarshub /etc/nginx/sites-enabled/acarshub || exit 1
    rm /etc/nginx/nginx.conf > /dev/null 2>&1  || exit 1
    cp /etc/nginx.acarshub/nginx.conf /etc/nginx/nginx.conf || exit 1
    rm -rv /etc/nginx.acarshub > /dev/null 2>&1 || exit 1
    rm /etc/nginx/sites-enabled/default > /dev/null 2>&1 || exit 1

    # turn off nginx logging
    # shellcheck disable=SC1003
    sed -i 's\access_log .*\access_log off;\' /etc/nginx/nginx.conf
    # shellcheck disable=SC1003
    sed -i 's\error_log .*\error_log /dev/null crit;\' /etc/nginx/nginx.conf

    #write the ADSB URL in to the nginx config file
    if [[ "${ENABLE_ADSB,,}" == "true" ]]; then
        # //&/\\& replaces & in query strings with \& so sed doesn't give it special meaning
        sed -i "s#<>#${ADSB_URL//&/\\&}#" /etc/nginx/sites-enabled/acarshub
        if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
            "${s6wrap[@]}" echo "ADSB enabled with ${ADSB_URL}"
        fi
    else
        sed -i "s\<>\\http://127.0.0.1:8888\\" /etc/nginx/sites-enabled/acarshub
        if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
            "${s6wrap[@]}" echo "ADSB Disabled"
        fi
    fi
else
    if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
        "${s6wrap[@]}" echo "Skipping nginx file configuring, container was restarted"
    fi
fi

touch /nginx-ranonce
