#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC1091
source /scripts/common

ACARSHUB_BIN="/opt/acarshub"

if [[ ${ENABLE_WEB,,} =~ true ]]; then
  if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
    # shellcheck disable=SC2016
    echo "Starting web service" | stdbuf -oL awk '{print "[webapp      ] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
  fi

  ACARSHUB_CMD=()

  # shellcheck disable=SC2016
  exec "${s6wrap[@]}" "${ACARSHUB_BIN}" "${ACARSHUB_CMD[@]}"
else
  # web server must be disabled. Go to sleep forever
  sleep 86400
fi
