#!/command/with-contenv bash
#shellcheck shell=bash
# shellcheck disable=SC2154

# shellcheck disable=SC1091
source /scripts/common

ACARSHUB_BIN="/opt/acarshub"

if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
  # shellcheck disable=SC2016
  "${s6wrap[@]}" echo "Starting ACARS Hub"
fi

ACARSHUB_CMD=()

# shellcheck disable=SC2016
exec "${s6wrap[@]}" "${ACARSHUB_BIN}" "${ACARSHUB_CMD[@]}"
