#!/command/with-contenv bash
#shellcheck shell=bash
# shellcheck disable=SC2154

# shellcheck disable=SC1091
source /scripts/common

if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
    # shellcheck disable=SC2016
    "${s6wrap[@]}" echo "Starting nginx"
fi

# shellcheck disable=SC2016
mkdir -p /var/log/nginx
# shellcheck disable=SC2016
exec "${s6wrap[@]}" /usr/sbin/nginx 2>&1
