#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [[ -n "$VERBOSE" ]]; then
    s6-setuidgid root /usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf || exit 0

    set -eo pipefail

    #shellcheck disable=SC2016
    s6-setuidgid root /usr/sbin/lighttpd \
        -f /etc/lighttpd/lighttpd.conf \
        -D \
        2>&1 | stdbuf -o0 awk '{print "[lighttpd] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    sleep 86400
fi
