#!/command/with-contenv bash
# shellcheck shell=bash

if [[ ! -e /nginx-ranonce ]]; then
    cp /etc/nginx.acarshub/sites-enabled/acarshub /etc/nginx/sites-enabled/acarshub || exit 1
    rm /etc/nginx/nginx.conf > /dev/null 2>&1  || exit 1
    cp /etc/nginx.acarshub/nginx.conf /etc/nginx/nginx.conf || exit 1
    rm -rv /etc/nginx.acarshub > /dev/null 2>&1 || exit 1
    rm /etc/nginx/sites-enabled/default > /dev/null 2>&1 || exit 1

    # turn off nginx logging
    # shellcheck disable=SC1003
    sed -i 's\access_log .*\access_log off;\' /etc/nginx/nginx.conf
    # shellcheck disable=SC1003
    sed -i 's\error_log .*\error_log /dev/null crit;\' /etc/nginx/nginx.conf

    #write the ADSB URL in to the nginx config file
    if [[ "${ENABLE_ADSB}" == "true" ]]; then
        sed -i "s\<>\\${ADSB_URL}\\" /etc/nginx/sites-enabled/acarshub
        if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
            echo "ADSB enabled with ${ADSB_URL}" | awk '{print "[03-nginx    ] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
        fi
    else
        sed -i "s\<>\\http://127.0.0.1:8888\\" /etc/nginx/sites-enabled/acarshub
        if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
            echo "ADSB Disabled" | awk '{print "[03-nginx    ] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
        fi
    fi
else
    if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
        echo "Skipping nginx file configuring, container was restarted" | awk '{print "[03-nginx    ] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi
fi

touch /nginx-ranonce
