#!/command/with-contenv bash
#shellcheck shell=bash

trap 'pkill -P $$' SIGTERM SIGINT SIGHUP SIGQUIT

if [[ ${ENABLE_WEB,,} =~ true ]]; then
  if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
    # shellcheck disable=SC2016
    echo "Starting web service" | stdbuf -oL awk '{print "[webapp      ] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
  fi

  pushd /webapp > /dev/null 2>&1 || exit 1

  # shellcheck disable=SC2016
  stdbuf -oL gunicorn \
      -b "0.0.0.0:8888" \
      -w 1 \
      --no-sendfile \
      -k eventlet \
      acarshub:app \
      --timeout 120 \
    2>&1 | stdbuf -oL sed --unbuffered '/^$/d' | \
    stdbuf -oL awk '! /\[[0-9]+\] \[INFO\]/' | \
    stdbuf -oL awk '{print "[webapp      ] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}' &

    wait || true
else
  # web server must be disabled. Go to sleep forever
  exec sleep infinity
fi
