[package]
name = "acarshub-server"
version.workspace = true
edition.workspace = true

[dependencies]
database = { path = "../database" }
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
