[package]
name = "acarshub-server"
version.workspace = true
edition.workspace = true

[dependencies]
acarshub-database = { path = "../acarshub-database" }
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
