[package]
name = "acarshub_webserver"
version.workspace = true
edition.workspace = true

[dependencies]
acarshub_database = { path = "../acarshub_database" }
anyhow.workspace = true
axum.workspace = true
parking_lot.workspace = true
tokio.workspace = true
tracing.workspace = true
