#!/usr/bin/with-contenv sh
#shellcheck shell=sh

if [ -n "${ENABLE_WEB}" ]; then
    if [ -z "${QUIET_LOGS}" ]; then
        # shellcheck disable=SC2016
        echo "Starting web proxy service" | stdbuf -o0 awk '{print "[nginx] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi

    # shellcheck disable=SC2016
    mkdir -p /var/log/nginx
    # shellcheck disable=SC2016
    exec \
    /usr/sbin/nginx 2>&1 | awk -W interactive '{print "[nginx] " $0}'
fi
