#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [[ ${ENABLE_WEB,,} =~ true ]]; then
    if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
        # shellcheck disable=SC2016
        echo "Starting web proxy service" | stdbuf -oL awk '{print "[nginx       ] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi

    # shellcheck disable=SC2016
    mkdir -p /var/log/nginx
    # shellcheck disable=SC2016
    exec \
    /usr/sbin/nginx 2>&1 | stdbuf -oL awk '{print "[nginx       ] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
fi
