[package]
name = "database"
version = "2.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
diesel.workspace = true
diesel_migrations.workspace = true
libsqlite3-sys.workspace = true
tracing.workspace = true
