[package]
name = "database"
version = "2.0.0"
edition.workspace = true

[dependencies]
diesel.workspace = true
diesel_migrations.workspace = true
libsqlite3-sys.workspace = true
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
