#!/usr/bin/with-contenv bash
#shellcheck shell=bash

VDLM_BIN="/usr/local/bin/vdlm2dec"
VDLM_CMD=("-J -G -E -U -g $GAIN -i $STATION_ID_VDLM")

if [ -n "${ENABLE_VDLM}" ]; then
	if [ -n "${VERBOSE}" ]; then
		VDLM_CMD+=("-l /run/acars/vdlm.json")
	fi

	if [ -n "${FEED}" ]; then
		VDLM_CMD+=("-j feed.acars.io:5555")
	fi

	if [ -n "${SERIAL_VDLM}" ]; then
		VDLM_CMD+=("-r $SERIAL_VDLM")
	else
		VDLM_CMD+=("-r 0")
	fi
	
	VDLM_CMD+=("$FREQS_VDLM")

	set -eo pipefail

	$VDLM_BIN ${VDLM_CMD[@]} \
	  2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[vdlm2dec] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
fi