#!/usr/bin/with-contenv bash
#shellcheck shell=bash

ACARS_BIN="/usr/local/bin/acarsdec"
ACARS_CMD=("-o 4 -g $GAIN -i $STATION_ID_ACARS")

if [ -n "${ENABLE_ACARS}" ]; then
	if [ -n "${VERBOSE}" ]; then
		ACARS_CMD+=("-l /run/acars/acars.json")
	fi

	if [ -n "${FEED}" ]; then
		ACARS_CMD+=("-j feed.acars.io:5550")
	fi

	if [ -n "${SERIAL_ACARS}" ]; then
		ACARS_CMD+=("-r $SERIAL_ACARS")
	else
		echo "[acarsdec] No serial number set. Using device index 0. If also running VDLM decoding one of these processes will fail. To fix, set SERIAL_ACARS and SERIAL_VDLM"
		ACARS_CMD+=("-r 0")
	fi

	# shellcheck disable=SC2001
    FREQS_ACARS=$(echo "$FREQS_ACARS" | sed 's/;/ /g')
	ACARS_CMD+=("$FREQS_ACARS")

	set -eo pipefail

	echo "[acarsdec] $ACARS_BIN" "${ACARS_CMD[@]}"

	"$ACARS_BIN" "${ACARS_CMD[@]}" \
	2>&1  | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[acarsdec] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    sleep 86400
fi