#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ${ENABLE_VDLM,,} =~ true ]]; then
  if [[ ${FEED,,} =~ true ]]; then
    # Don't do anything because dumpvdl2 is not compabile with airframes right now.
    # We'll handle this elsewhere.
    sleep 86400

    # set -o pipefail

    # # Require that vdlm2_server is running
    # if ! netstat -an | grep -P '^\s*tcp\s+\d+\s+\d+\s+0.0\.0\.0:15555\s+(?>\d{1,3}\.{0,1}){4}:\*\s+LISTEN\s*$' > /dev/null; then
    #   if [ -z "${QUIET_LOGS}" ]; then
    #     # shellcheck disable=SC2016
    #     echo "Waiting for vdlm2_server" | stdbuf -oL awk '{print "[vdlm2_feeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    #   fi
    #   sleep 1
    #   exit
    # fi
    # if [ -z "${QUIET_LOGS}" ]; then
    #   # shellcheck disable=SC2016
    #   echo "vdlm2_server ready, starting service" | stdbuf -oL awk '{print "[vdlm2_feeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    # fi

    # set -e

    # # Start the feed - take JSON messages from TCP port 15555 and send them to feed.acars.io UDP port 5555
    # # shellcheck disable=SC2016
    # socat -d TCP:127.0.0.1:15555 UDP:feed.acars.io:5555 \
    #   2>&1 | stdbuf -oL awk '{print "[vdlm2_feeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

  else
    sleep 86400
  fi
else
  sleep 86400
fi
