#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# STARTUP SEQUENCE
#  - acarsdec does not depend on any services and should start immediately

ACARS_BIN="/usr/local/bin/acarsdec"
DEVICE_ID=""
SERIAL=""
# shellcheck disable=SC2001
FREQS_ACARS=""
PPM=""
GAIN=""
RTLMULT=""

if [ -z "$GAIN" ]; then
    GAIN="-10"
fi

ACARS_CMD=("-g" "$GAIN" "-i" "$STATION_ID_ACARS")

if [ -n "${PPM}" ]; then
	ACARS_CMD+=("-p" "$PPM")
fi

if [ -n "${QUIET_MESSAGES}" ]; then
	ACARS_CMD+=("-o" "0")
	ACARS_CMD+=("-l" "/dev/null")
else
	ACARS_CMD+=("-o" "4")
	ACARS_CMD+=("-v")
fi

if [ -n "${RTLMULT}" ]; then
	ACARS_CMD+=("-m" "$RTLMULT")
fi

# Send output JSON to acars_server
ACARS_CMD+=("-j" '127.0.0.1:5550')

# Specify device ID
if [ -n "${DEVICE_ID}" ]; then
	ACARS_CMD+=("-r" "$DEVICE_ID")
else
	echo "[acarsdec-$SERIAL] No serial number / device index set. Using device index 0. If also running VDLM decoding one of these processes will fail. To fix, set SERIAL_ACARS and SERIAL_VDLM"
	ACARS_CMD+=("-r" "0")
fi

# shellcheck disable=SC2206
ACARS_CMD+=($FREQS_ACARS)

set -eo pipefail

if [[ -n "${QUIET_LOGS}" ]]; then
  # shellcheck disable=SC2016
  "$ACARS_BIN" "${ACARS_CMD[@]}" 2>&1 | \
  stdbuf -oL sed --unbuffered '/^$/d' | \
  stdbuf -oL awk '! /^dumpvdl2/' | \
  stdbuf -oL awk '! /^Sampling rate set/' | \
  stdbuf -oL awk '! /^Found \d+ device(s):/' | \
  stdbuf -oL awk '! /^  [0-9]+/' | \
  stdbuf -oL awk '! /^Using device [0-9]+/' | \
  stdbuf -oL awk '! /^Found /' | \
  stdbuf -oL awk '! /^Exact sample rate /' | \
  stdbuf -oL awk '! /^Setting sample rate/' | \
  stdbuf -oL awk '! /PLL not locked!$/' | \
  stdbuf -oL awk '! /^Center frequency set/' | \
  stdbuf -oL awk '! /^Device [#]?[0-9]+/' | \
  stdbuf -oL awk '! /^Tuner gain: /' | \
  stdbuf -oL awk '! /^Set center freq. /' | \
  stdbuf -oL awk '! /^Decoding [0-9]+ channels/' | \
  stdbuf -oL awk '{print "[acarsdec] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
  echo "[acarsdec-$SERIAL] Starting: '$ACARS_BIN" "${ACARS_CMD[*]}'"
  # shellcheck disable=SC2016
  "$ACARS_BIN" "${ACARS_CMD[@]}" 2>&1 | \
  stdbuf -oL sed --unbuffered '/^$/d' | \
  stdbuf -oL awk '{print "[acarsdec] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
fi

# if we've ended up here there is a problem!

echo "[acarsdec-$SERIAL] Exiting with error"
sleep 5
exit 1