#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [[ -n "${ENABLE_ACARS}" ]]; then

  set -o pipefail

  # Require that acars_server is running
  if ! netstat -an | grep -P '^\s*tcp\s+\d+\s+\d+\s+127\.0\.0\.1:15550\s+(?>\d{1,3}\.{0,1}){4}:\*\s+LISTEN\s*$' > /dev/null; then
    if [ -n "${VERBOSE}" ]; then
      # shellcheck disable=SC2016
      echo "Waiting for acars_server" | stdbuf -o0 awk '{print "[acars_stats] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi
    sleep 1
    exit
  fi
  if [ -n "${VERBOSE}" ]; then
    # shellcheck disable=SC2016
    echo "acars_server ready, starting service" | stdbuf -o0 awk '{print "[acars_stats] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
  fi

  # Start our stats loop
  while true; do

    # capture 5 mins of flows
    timeout 300s socat -u TCP:127.0.0.1:15550 CREATE:/run/acars/acars.past5min.json

    # shellcheck disable=SC2016
    echo "$(wc -l < /run/acars/acars.past5min.json) ACARS messages received in last 5 mins" | stdbuf -o0 awk '{print "[acars_stats] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

    # rotate files keeping last 2 hours
    for i in {24..1}; do
      mv "/run/acars/acars.$((i-1)).json" "/run/acars/acars.$i.json" > /dev/null 2>&1 || true
    done
    mv "/run/acars/acars.past5min.json" "/run/acars/acars.0.json" > /dev/null 2>&1 || true

  done
  
else

  # If here then VDLM2 is not enabled, sleep forever
  sleep 86400
fi
