[package]
name = "acarshub-settings"
version.workspace = true
edition.workspace = true

[dependencies]
acarshub-message-processing = { path = "../acarshub-message-processing" }
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
