#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[  ${ENABLE_ACARS,,} =~ external ]]; then
  if [[  ${FEED,,} =~ true ]]; then
    sleep 86400
    # set -o pipefail

    # # Require that acars_server is running
    # if ! netstat -an | grep -P '^\s*tcp\s+\d+\s+\d+\s+0\.0\.0\.0:15550\s+(?>\d{1,3}\.{0,1}){4}:\*\s+LISTEN\s*$' > /dev/null; then
    #   if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
    #     # shellcheck disable=SC2016
    #     echo "Waiting for acars_server" | stdbuf -oL awk '{print "[acars_feeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    #   fi
    #   sleep 1
    #   exit
    # fi
    # if [[ $((MIN_LOG_LEVEL)) -ge 4 ]]; then
    #   # shellcheck disable=SC2016
    #   echo "acars_server ready, starting service" | stdbuf -oL awk '{print "[acars_feeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    # fi

    # set -e

    # # Start the feed - take JSON messages from TCP port 15550 and send them to feed.acars.io UDP port 5550
    # # shellcheck disable=SC2016
    # socat -d TCP:127.0.0.1:15550 UDP:feed.acars.io:5550 \
    #   2>&1 | stdbuf -oL awk '{print "[acars_feeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

  else
    sleep 86400
  fi
else
  sleep 86400
fi
