"""create_alert_matches_table

Revision ID: 171fe2c07bd9
Revises: 204a67756b9a
Create Date: 2026-02-05 16:45:12.345678

This migration creates a normalized alert_matches junction table to replace
the denormalized messages_saved table. This eliminates data duplication by
storing only the alert metadata (term, match_type, timestamp) instead of
duplicating all 30+ message fields.

Schema changes:
- Creates alert_matches table with message_uid foreign key
- Drops messages_saved table (old data NOT migrated - clean slate)

Why not migrate old data:
- messages_saved rows have no UID (previous migration only added UID to messages table)
- messages_saved rows cannot be reliably linked to messages rows
- Old alert data is stale and will not be shown in new system
- New alerts will be generated going forward by backend alert matching

Benefits:
- No data duplication (one message stored once)
- Storage efficient (message matching N terms = 1 message + N alert rows)
- Consistent data (updates to messages table immediately reflect everywhere)
- Same UID always refers to same message
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "171fe2c07bd9"
down_revision: Union[str, Sequence[str], None] = "204a67756b9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create normalized alert_matches table and drop messages_saved.

    Note: Old messages_saved data is NOT migrated because:
    1. messages_saved rows have no UID (previous migration only added to messages table)
    2. Cannot reliably link messages_saved rows to messages rows
    3. Old alert data is stale anyway (messages already processed)
    4. New system will generate alerts going forward
    """

    # Create new alert_matches table (normalized schema)
    op.create_table(
        "alert_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_uid", sa.String(36), nullable=False),
        sa.Column("term", sa.String(32), nullable=False),
        sa.Column("match_type", sa.String(32), nullable=False),
        sa.Column("matched_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create index on message_uid for fast JOIN queries with messages table
    op.create_index("ix_alert_matches_message_uid", "alert_matches", ["message_uid"])

    # DO NOT migrate old data from messages_saved - it has no UIDs and cannot be linked
    # Old alerts will not appear in the new system (clean slate)
    # New alerts will be generated by backend going forward

    # Drop the denormalized messages_saved table
    # Old alert data is discarded (users can still see messages in messages table)
    # SQLite automatically drops indexes when dropping the table
    op.drop_table("messages_saved")


def downgrade() -> None:
    """Restore empty messages_saved table (for rollback compatibility).

    Note: We only restore the table structure, not data, because:
    1. No data was migrated in upgrade (clean slate approach)
    2. alert_matches rows cannot be denormalized without duplicating message data
    3. Downgrade should be rare (only for testing or emergency rollback)
    """

    # Recreate messages_saved table with full schema (but no data)
    op.create_table(
        "messages_saved",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_type", sa.String(32), nullable=False),
        sa.Column("msg_time", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.String(32), nullable=False),
        sa.Column("toaddr", sa.String(32), nullable=False),
        sa.Column("fromaddr", sa.String(32), nullable=False),
        sa.Column("depa", sa.String(32), nullable=False),
        sa.Column("dsta", sa.String(32), nullable=False),
        sa.Column("eta", sa.String(32), nullable=False),
        sa.Column("gtout", sa.String(32), nullable=False),
        sa.Column("gtin", sa.String(32), nullable=False),
        sa.Column("wloff", sa.String(32), nullable=False),
        sa.Column("wlin", sa.String(32), nullable=False),
        sa.Column("lat", sa.String(32), nullable=False),
        sa.Column("lon", sa.String(32), nullable=False),
        sa.Column("alt", sa.String(32), nullable=False),
        sa.Column("msg_text", sa.Text(), nullable=False),
        sa.Column("tail", sa.String(32), nullable=False),
        sa.Column("flight", sa.String(32), nullable=False),
        sa.Column("icao", sa.String(32), nullable=False),
        sa.Column("freq", sa.String(32), nullable=False),
        sa.Column("ack", sa.String(32), nullable=False),
        sa.Column("mode", sa.String(32), nullable=False),
        sa.Column("label", sa.String(32), nullable=False),
        sa.Column("block_id", sa.String(32), nullable=False),
        sa.Column("msgno", sa.String(32), nullable=False),
        sa.Column("is_response", sa.String(32), nullable=False),
        sa.Column("is_onground", sa.String(32), nullable=False),
        sa.Column("error", sa.String(32), nullable=False),
        sa.Column("libacars", sa.Text(), nullable=False),
        sa.Column("level", sa.String(32), nullable=False),
        sa.Column("term", sa.String(32), nullable=False),
        sa.Column("type_of_match", sa.String(32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Recreate indexes (even though table is empty)
    with op.batch_alter_table("messages_saved", schema=None) as batch_op:
        batch_op.create_index("ix_messages_saved_depa", ["depa"], unique=False)
        batch_op.create_index("ix_messages_saved_dsta", ["dsta"], unique=False)
        batch_op.create_index("ix_messages_saved_flight", ["flight"], unique=False)
        batch_op.create_index("ix_messages_saved_freq", ["freq"], unique=False)
        batch_op.create_index("ix_messages_saved_icao", ["icao"], unique=False)
        batch_op.create_index("ix_messages_saved_label", ["label"], unique=False)
        batch_op.create_index("ix_messages_saved_msg_text", ["msg_text"], unique=False)
        batch_op.create_index("ix_messages_saved_msgno", ["msgno"], unique=False)
        batch_op.create_index("ix_messages_saved_tail", ["tail"], unique=False)

    # Do NOT restore data - table is empty after downgrade
    # If you need old alert data, restore from database backup

    # Drop alert_matches table
    op.drop_index("ix_alert_matches_message_uid", table_name="alert_matches")
    op.drop_table("alert_matches")
