"""Initial schema

Revision ID: e7991f1644b1
Revises: 
Create Date: 2026-02-02 11:23:52.184830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7991f1644b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('good', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freqs',
    sa.Column('it', sa.Integer(), nullable=False),
    sa.Column('freq', sa.String(length=32), nullable=True),
    sa.Column('freq_type', sa.String(length=32), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('it')
    )
    op.create_table('ignore_alert_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('msg_time', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=32), nullable=False),
    sa.Column('toaddr', sa.String(length=32), nullable=False),
    sa.Column('fromaddr', sa.String(length=32), nullable=False),
    sa.Column('depa', sa.String(length=32), nullable=False),
    sa.Column('dsta', sa.String(length=32), nullable=False),
    sa.Column('eta', sa.String(length=32), nullable=False),
    sa.Column('gtout', sa.String(length=32), nullable=False),
    sa.Column('gtin', sa.String(length=32), nullable=False),
    sa.Column('wloff', sa.String(length=32), nullable=False),
    sa.Column('wlin', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.String(length=32), nullable=False),
    sa.Column('lon', sa.String(length=32), nullable=False),
    sa.Column('alt', sa.String(length=32), nullable=False),
    sa.Column('msg_text', sa.Text(), nullable=False),
    sa.Column('tail', sa.String(length=32), nullable=False),
    sa.Column('flight', sa.String(length=32), nullable=False),
    sa.Column('icao', sa.String(length=32), nullable=False),
    sa.Column('freq', sa.String(length=32), nullable=False),
    sa.Column('ack', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('block_id', sa.String(length=32), nullable=False),
    sa.Column('msgno', sa.String(length=32), nullable=False),
    sa.Column('is_response', sa.String(length=32), nullable=False),
    sa.Column('is_onground', sa.String(length=32), nullable=False),
    sa.Column('error', sa.String(length=32), nullable=False),
    sa.Column('libacars', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_depa'), ['depa'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_dsta'), ['dsta'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_flight'), ['flight'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_freq'), ['freq'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_icao'), ['icao'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_msg_text'), ['msg_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_msgno'), ['msgno'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_tail'), ['tail'], unique=False)

    op.create_table('messages_saved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('msg_time', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=32), nullable=False),
    sa.Column('toaddr', sa.String(length=32), nullable=False),
    sa.Column('fromaddr', sa.String(length=32), nullable=False),
    sa.Column('depa', sa.String(length=32), nullable=False),
    sa.Column('dsta', sa.String(length=32), nullable=False),
    sa.Column('eta', sa.String(length=32), nullable=False),
    sa.Column('gtout', sa.String(length=32), nullable=False),
    sa.Column('gtin', sa.String(length=32), nullable=False),
    sa.Column('wloff', sa.String(length=32), nullable=False),
    sa.Column('wlin', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.String(length=32), nullable=False),
    sa.Column('lon', sa.String(length=32), nullable=False),
    sa.Column('alt', sa.String(length=32), nullable=False),
    sa.Column('msg_text', sa.Text(), nullable=False),
    sa.Column('tail', sa.String(length=32), nullable=False),
    sa.Column('flight', sa.String(length=32), nullable=False),
    sa.Column('icao', sa.String(length=32), nullable=False),
    sa.Column('freq', sa.String(length=32), nullable=False),
    sa.Column('ack', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('block_id', sa.String(length=32), nullable=False),
    sa.Column('msgno', sa.String(length=32), nullable=False),
    sa.Column('is_response', sa.String(length=32), nullable=False),
    sa.Column('is_onground', sa.String(length=32), nullable=False),
    sa.Column('error', sa.String(length=32), nullable=False),
    sa.Column('libacars', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=False),
    sa.Column('type_of_match', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages_saved', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_saved_depa'), ['depa'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_saved_dsta'), ['dsta'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_saved_flight'), ['flight'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_saved_freq'), ['freq'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_saved_icao'), ['icao'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_saved_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_saved_msg_text'), ['msg_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_saved_msgno'), ['msgno'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_saved_tail'), ['tail'], unique=False)

    op.create_table('nonlogged_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('good', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonlogged_count')
    with op.batch_alter_table('messages_saved', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_saved_tail'))
        batch_op.drop_index(batch_op.f('ix_messages_saved_msgno'))
        batch_op.drop_index(batch_op.f('ix_messages_saved_msg_text'))
        batch_op.drop_index(batch_op.f('ix_messages_saved_label'))
        batch_op.drop_index(batch_op.f('ix_messages_saved_icao'))
        batch_op.drop_index(batch_op.f('ix_messages_saved_freq'))
        batch_op.drop_index(batch_op.f('ix_messages_saved_flight'))
        batch_op.drop_index(batch_op.f('ix_messages_saved_dsta'))
        batch_op.drop_index(batch_op.f('ix_messages_saved_depa'))

    op.drop_table('messages_saved')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_tail'))
        batch_op.drop_index(batch_op.f('ix_messages_msgno'))
        batch_op.drop_index(batch_op.f('ix_messages_msg_text'))
        batch_op.drop_index(batch_op.f('ix_messages_label'))
        batch_op.drop_index(batch_op.f('ix_messages_icao'))
        batch_op.drop_index(batch_op.f('ix_messages_freq'))
        batch_op.drop_index(batch_op.f('ix_messages_flight'))
        batch_op.drop_index(batch_op.f('ix_messages_dsta'))
        batch_op.drop_index(batch_op.f('ix_messages_depa'))

    op.drop_table('messages')
    op.drop_table('level')
    op.drop_table('ignore_alert_terms')
    op.drop_table('freqs')
    op.drop_table('count')
    op.drop_table('alert_stats')
    # ### end Alembic commands ###
