[package]
name = "acarshub"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
acarshub_database.workspace = true
acarshub_settings.workspace = true
acarshub_webserver.workspace = true
acarshub_message_processing.workspace = true
parking_lot.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
