#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [ -n "${PLANEPLOTTER}" ] && [ -n "$ENABLE_VDLM" ]; then

  set -o pipefail

  if [ -z "${QUIET_LOGS}" ]; then
    # shellcheck disable=SC2016
    echo "Starting service" | stdbuf -oL awk '{print "[planeplotter_server] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
  fi

  set -e

  # Listen for the output of dumpvdl2 PP (UDP), and make it available for multiple processes at TCP port 14444
  # shellcheck disable=SC2016
  socat -u udp-listen:4444,fork stdout | ncat -4 --keep-open --listen 0.0.0.0 14444 \
    2>&1 | stdbuf -oL awk '{print "[planeplotter_server] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
  sleep 86400
fi
