#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [ -n "${ENABLE_VDLM}" ]; then

  set -o pipefail

  if [ -z "${QUIET_LOGS}" ]; then
    # shellcheck disable=SC2016
    echo "Starting service" | stdbuf -oL awk '{print "[vdlm2_server] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
  fi

  set -e

  # Listen for the output of vdlm2dec (UDP), and make it available for multiple processes at TCP port 15555
  # shellcheck disable=SC2016
  socat -u udp-listen:5555,fork stdout | ncat -4 --keep-open --listen 0.0.0.0 15555 \
    2>&1 | stdbuf -oL awk '{print "[vdlm2_server] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
  sleep 86400
fi
