#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# create the /run/acars dir
mkdir -p /run/acars/

FREQ_CMD=()

# we do the sanity checking of the env variables in python because I cannot stomach the idea of doing this in bash any more

pushd ../../scripts > /dev/null 2>&1 || exit 1
python3 acars-sanity-checker.py || exit 1

if [ -n "${ENABLE_ACARS}" ]; then
	if [ -n "${FREQS_ACARS}" ]; then
		IFS=';' read -r -a ACARS_ARRAY <<< "$FREQS_ACARS"
		FREQ_CMD+=("-a" "${ACARS_ARRAY[@]}")
	fi
fi

if [ -n "${ENABLE_VDLM}" ]; then
	if [ -n "${FREQS_VDLM}" ]; then
		IFS=';' read -r -a VDLM_ARRAY <<< "$FREQS_VDLM"
		FREQ_CMD+=("-v" "${VDLM_ARRAY[@]}")
	fi
fi

if [ -n "${SERIAL}" ]; then
	IFS=';' read -r -a SERIAL_ARRAY <<< "$SERIAL"
	FREQ_CMD+=("-s" "${SERIAL_ARRAY[@]}")
fi

echo "Generating decoder startup files" | awk '{print "[01-acarshub] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

# Just in case the container was docker restart we should clean up some dirs if present
# thanks k1xt

rm -rf /etc/services.d/acarsdec-* /etc/services.d/vdlm2dec-* >/dev/null 2>&1
# shellcheck disable=SC2016
python3 assign_frequencies.py "${FREQ_CMD[@]}" | stdbuf -oL awk '{print "[01-acarshub] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}' || exit 1

if [[ ! -e /ranonce ]]; then
	echo "Renaming files" | awk '{print "[01-acarshub] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
	# shellcheck disable=SC2016
	python3 rename_files.py | stdbuf -oL awk '{print "[01-acarshub] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}' || exit 1
else
	echo "Skipping file renaming. Container was restarted" | awk '{print "[01-acarshub] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
fi

# Ensure /database dir is present

mkdir -p /database/images/static/images

# Ensure stats files are present
touch /database/vdlm2.past5min.json
touch /database/acars.past5min.json
# file to flag if the file rename has been done already, in case of container restart
touch /ranonce

exit 0
