#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# create the /run/acars dir

mkdir -p /run/acars/

FREQ_CMD=()

if [ -n "${GAIN}" ]; then
	echo "Error. Please use GAIN_ACARS and GAIN_VDLM to set the gain."
fi

if [ -n "$SERIAL_ACARS" ]; then
	echo "Error: Please see the github readme for update useage."
	exit 1
fi

if [ -n "$SERIAL_VDLM" ]; then
	echo "Error: Please see the github readme for update useage."
	exit 1
fi

if [ -n "${ENABLE_ACARS}" ]; then
	if [ -z "${STATION_ID_ACARS}" ]; then
		echo "Error: ACARS enabled with no STATION_ID_ACARS set. Exiting"
		exit 1
	fi

	if [ -n "${FREQS_ACARS}" ]; then
		FREQ_CMD+=("-a" $(echo $FREQS_ACARS | sed 's/;/ /g'))
	elif [ -z "${ACARS_FREQ_0}" ]; then
		echo "Error: ACARS enabled with no FREQS_ACARS. Exiting"
		exit 1
	fi
fi

if [ -n "${ENABLE_VDLM}" ]; then
	if [ -z "${STATION_ID_VDLM}" ]; then
		echo "Error: VDLM enabled with no STATION_ID_VDLM set. Exiting"
		exit 1
	fi
	if [ -n "${FREQS_VDLM}" ]; then
		FREQ_CMD+=("-v" $(echo $FREQS_VDLM | sed 's/;/ /g'))
	elif [ -z "${VDLM_FREQ_0}" ]; then
		echo "Error: VDLM enabled with no FREQS_VDLM. Exiting"
		exit 1
	fi
fi

FREQ_CMD+=("-s" $(echo $SERIAL | sed 's/;/ /g'))
echo "${FREQ_CMD[@]}"
echo "Generating decoder startup files"

pushd ../../scripts
python3 assign_frequencies.py "${FREQ_CMD[@]}"



#FREQS_VDLM=$(echo "$FREQS_VDLM" | sed 's/;/ /g')
# Ensure stats files are present
touch /run/acars/vdlm2.past5min.json
touch /run/acars/acars.past5min.json

exit 0
