#!/usr/bin/with-contenv sh
# shellcheck shell=sh

# create the /run/acars dir

mkdir -p /run/acars/

if [ -n "${ENABLE_ACARS}" ]; then
	if [ -z "${STATION_ID_ACARS}" ]; then
		echo "Error: ACARS enabled with no STATION_ID_ACARS set. Exiting"
		exit 1
	fi

	if [ -z "${FREQS_ACARS}" ]; then
		echo "Error: ACARS enabled with no FREQS_ACARS. Exiting"
		exit 1
	fi
fi

if [ -n "${ENABLE_VDLM}" ]; then
	if [ -z "${STATION_ID_VDLM}" ]; then
		echo "Error: VDLM enabled with no STATION_ID_VDLM set. Exiting"
		exit 1
	fi
	if [ -z "${FREQS_VDLM}" ]; then
		echo "Error: VDLM enabled with no FREQS_VDLM. Exiting"
		exit 1
	fi
fi

exit 0
