#!/usr/bin/with-contenv sh
# shellcheck shell=sh

TIME=$(date +%s)
TIME=$((TIME-100))

if [ ! -f "/run/acars/acars.rrd" ]; then
    rrdtool create /run/acars/acars.rrd            \
    --start $TIME \
    DS:ACARS:GAUGE:600:U:U \
    RRA:AVERAGE:0.5:1:120 \
    RRA:AVERAGE:0.5:2:120 \
    RRA:AVERAGE:0.5:4:120 \
    RRA:AVERAGE:0.5:10:288 \
    RRA:AVERAGE:0.5:20:1008 \
    RRA:AVERAGE:0.5:60:1440 \
    RRA:AVERAGE:0.5:80:3240 \
    RRA:AVERAGE:0.5:100:5184 \
    RRA:AVERAGE:0.5:120:8760 \
    RRA:AVERAGE:0.5:240:8760 \
    RRA:AVERAGE:0.5:360:8760 \
    RRA:MAX:0.5:1:120 \
    RRA:MAX:0.5:2:120 \
    RRA:MAX:0.5:4:120 \
    RRA:MAX:0.5:10:288 \
    RRA:MAX:0.5:20:1008 \
    RRA:MAX:0.5:60:1440 \
    RRA:MAX:0.5:80:3240 \
    RRA:MAX:0.5:100:5184 \
    RRA:MAX:0.5:120:8760 \
    RRA:MAX:0.5:240:8760 \
    RRA:MAX:0.5:360:8760 \
    RRA:LAST:0.5:1:120 \
    RRA:LAST:0.5:2:120 \
    RRA:LAST:0.5:4:120 \
    RRA:LAST:0.5:10:288 \
    RRA:LAST:0.5:20:1008 \
    RRA:LAST:0.5:60:1440 \
    RRA:LAST:0.5:80:3240 \
    RRA:LAST:0.5:100:5184 \
    RRA:LAST:0.5:120:8760 \
    RRA:LAST:0.5:240:8760 \
    RRA:LAST:0.5:360:8760
fi

if [ ! -f "/run/acars/vdlm.rrd" ]; then
    rrdtool create /run/acars/vdlm.rrd            \
    --start $TIME \
    DS:ACARS:GAUGE:600:U:U \
    RRA:AVERAGE:0.5:1:120 \
    RRA:AVERAGE:0.5:2:120 \
    RRA:AVERAGE:0.5:4:120 \
    RRA:AVERAGE:0.5:10:288 \
    RRA:AVERAGE:0.5:20:1008 \
    RRA:AVERAGE:0.5:60:1440 \
    RRA:AVERAGE:0.5:80:3240 \
    RRA:AVERAGE:0.5:100:5184 \
    RRA:AVERAGE:0.5:120:8760 \
    RRA:AVERAGE:0.5:240:8760 \
    RRA:AVERAGE:0.5:360:8760 \
    RRA:MAX:0.5:1:120 \
    RRA:MAX:0.5:2:120 \
    RRA:MAX:0.5:4:120 \
    RRA:MAX:0.5:10:288 \
    RRA:MAX:0.5:20:1008 \
    RRA:MAX:0.5:60:1440 \
    RRA:MAX:0.5:80:3240 \
    RRA:MAX:0.5:100:5184 \
    RRA:MAX:0.5:120:8760 \
    RRA:MAX:0.5:240:8760 \
    RRA:MAX:0.5:360:8760 \
    RRA:LAST:0.5:1:120 \
    RRA:LAST:0.5:2:120 \
    RRA:LAST:0.5:4:120 \
    RRA:LAST:0.5:10:288 \
    RRA:LAST:0.5:20:1008 \
    RRA:LAST:0.5:60:1440 \
    RRA:LAST:0.5:80:3240 \
    RRA:LAST:0.5:100:5184 \
    RRA:LAST:0.5:120:8760 \
    RRA:LAST:0.5:240:8760 \
    RRA:LAST:0.5:360:8760
fi