#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cp /etc/nginx.acarshub/sites-enabled/acarshub /etc/nginx/sites-enabled/acarshub || exit 1
rm /etc/nginx/nginx.conf  || exit 1
cp /etc/nginx.acarshub/nginx.conf /etc/nginx/nginx.conf || exit 1
rm -rv /etc/nginx.acarshub || exit 1
rm /etc/nginx/sites-enabled/default || exit 1
# shellcheck disable=SC1003
sed -i 's\access_log .*\access_log off;\' /etc/nginx/nginx.conf
# shellcheck disable=SC1003
sed -i 's\error_log .*\error_log /dev/null crit;\' /etc/nginx/nginx.conf
