name: Sync dockerhub readme

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  syncreadme:
    name: Sync Readme
    runs-on: ubuntu-latest
    steps:
    -
      name: sync readme to dockerhub
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: fredclausen/acarshub
        readme: "./README.md"
