name: Sync dockerhub readme

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

syncreadme:
  name: Sync Readme
  uses: ms-jpq/sync-dockerhub-readme@v1
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}
    repository: fredclausen/acarshub
    readme: "./README.md"
